sudo: required
language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4.5
    - otp_release: 19.2
      elixir: 1.5.3
    - otp_release: 20.2
      elixir: 1.6.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install libc-ares-dev libssl-dev uuid-dev
  - wget http://mirror.switch.ch/eclipse/mosquitto/source/mosquitto-1.4.12.tar.gz
install:
  - tar xvzf mosquitto-1.4.12.tar.gz
  - cd mosquitto-1.4.12
  - make
  - sudo make install
  - cd ..
  - sudo cp -R ./mosquitto/certs/ /etc/mosquitto/certs/
  - sudo cp ./mosquitto/mosquitto.conf /etc/mosquitto/mosquitto.conf
before_script:
  - mosquitto -d -c /etc/mosquitto/mosquitto.conf
  - mix local.hex --force
  - mix local.rebar
  - MIX_ENV=test mix deps.get
script:
  - sleep 10
  - MIX_ENV=test mix test
after_script:
  - MIX_ENV=test mix coveralls.travis
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
